Support/metamask
cennznet/api.js pull request #465
Opened 2022-04-27 04:50 UTC by KarishmaBothara

Closes https://github.com/cennznet/api.js/issues/463
Detail - with this PR, user can use CENNZnet API to sign tx with Metamask wallet. 
Users eth address should have CPAY to do a CENNZnet operation. The call required is as simple as
```
await api.tx.genericAsset
            .transfer(stakingAssetId, alice.address, transferAmt)
            .signViaMetaMask(
                ethAddress,
                api
            );
```
ethAddress - Ethereum address on metamask

2022-04-27 05:20 UTC, holygits reviewed
cool! drive by review :)

2022-04-27 05:20 UTC, holygits commented on packages/types/src/interfaces/extrinsic/v1/Extrinsic.ts
> +  }
should make this function available to package users

2022-04-27 05:20 UTC, holygits commented on packages/types/src/interfaces/extrinsic/v1/Extrinsic.ts
> +  async signViaMetaMask(ethAddress: string, api: Api): Promise<SubmittableResultResult<ApiTypes>> {
name shouldn't be 'metamask'
other ethereum wallets can use this too: https://docs.walletconnect.com/json-rpc-api-methods/ethereum

2022-04-29 01:57 UTC, ken-centrality requested changes
should we have test for the new extrinsic method `signViaEthWallet` and the `cvmToAddress` function?

2022-04-29 01:57 UTC, ken-futureverse commented on packages/types/src/interfaces/augment-types.ts
> +    ethWalletCall: ethWalletCall;
nitpick but should this be `EthWalletCall` with capital `E`?

2022-04-29 01:57 UTC, ken-futureverse commented on packages/types/src/interfaces/extrinsic/v1/Extrinsic.ts
> +    const ethereum = typeof (global as any).ethereum !== "undefined" ? (global as any).ethereum : (window as any).ethereum;
I still think we should have the `ethereum` as parameter, would make it so much easier to mock test plus it doesn't care if `ethereum` is from `global` or `window`

2022-05-01 21:12 UTC, KarishmaBothara commented
> should we have test for the new extrinsic method `signViaEthWallet` and the `cvmToAddress` function?

we have one for signViaEthWallet here - https://github.com/cennznet/api.js/blob/support/Metamask/packages/api/test/e2e/tx.e2e.ts#L130
can add one for cvmToAddress function

2022-05-01 22:36 UTC, ken-centrality approved these changes

2022-05-02 02:06 UTC, merged